// src/components/TrailsModal/TrailsModal.styles.js
import { StyleSheet } from 'react-native';
import { Colors, Fonts, ColorUtils } from '../../theme/theme';

export const createStyles = (isDarkMode) => StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.overlayBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: ColorUtils.getThemeColor(Colors.modalBackground, Colors.modalBackgroundDark, isDarkMode),
    borderRadius: 16,
    padding: 24,
    width: '92%',
    maxHeight: '85%',
    elevation: 20,
    shadowColor: Colors.shadowDark,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    borderWidth: 1,
    borderColor: ColorUtils.getThemeColor(Colors.borderLight, Colors.borderDark, isDarkMode),
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: ColorUtils.getThemeColor(Colors.borderMedium, Colors.borderDark, isDarkMode),
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: ColorUtils.getThemeColor(Colors.textPrimary, Colors.textPrimaryDark, isDarkMode),
    fontFamily: Fonts.heading,
  },
  closeButton: {
    backgroundColor: ColorUtils.getThemeColor(Colors.cardBackground, Colors.cardBackgroundDark, isDarkMode),
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: Colors.shadowMedium,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    borderWidth: 1,
    borderColor: ColorUtils.getThemeColor(Colors.borderLight, Colors.borderDark, isDarkMode),
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  emptyText: {
    fontSize: 16,
    color: ColorUtils.getThemeColor(Colors.textMuted, Colors.textMutedDark, isDarkMode),
    textAlign: 'center',
    marginTop: 16,
    fontFamily: Fonts.body,
    lineHeight: 24,
  },
  trailItem: {
    backgroundColor: ColorUtils.getThemeColor(Colors.backgroundSecondary, Colors.backgroundSecondaryDark, isDarkMode),
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: ColorUtils.getThemeColor(Colors.borderLight, Colors.borderDark, isDarkMode),
    elevation: 8,
    shadowColor: Colors.shadowMedium,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  trailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  trailInfo: {
    flex: 1,
    marginRight: 12,
  },
  trailName: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: Fonts.bodyBold,
    marginBottom: 4,
    lineHeight: 22,
    color: ColorUtils.getThemeColor(Colors.textPrimary, Colors.textPrimaryDark, isDarkMode),
  },
  trailDate: {
    fontSize: 13,
    fontFamily: Fonts.caption,
    lineHeight: 18,
    color: ColorUtils.getThemeColor(Colors.textMuted, Colors.textMutedDark, isDarkMode),
  },
  editInput: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: Fonts.bodyBold,
    borderWidth: 2,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 4,
    color: ColorUtils.getThemeColor(Colors.textPrimary, Colors.textPrimaryDark, isDarkMode),
    borderColor: ColorUtils.getThemeColor(Colors.borderFocus, Colors.blue400, isDarkMode),
    backgroundColor: ColorUtils.getThemeColor(Colors.inputBackground, Colors.inputBackgroundDark, isDarkMode),
  },
  visibilityContainer: {
    alignItems: 'center',
    minWidth: 60,
  },
  visibilityLabel: {
    fontSize: 11,
    fontFamily: Fonts.caption,
    marginBottom: 6,
    textAlign: 'center',
    color: ColorUtils.getThemeColor(Colors.textMuted, Colors.textMutedDark, isDarkMode),
  },
  trailStats: {
    flexDirection: 'row',
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
    marginBottom: 4,
  },
  statText: {
    fontSize: 13,
    fontFamily: Fonts.body,
    marginLeft: 6,
    color: ColorUtils.getThemeColor(Colors.textSecondary, Colors.textSecondaryDark, isDarkMode),
  },
  trailActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 8,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    minWidth: 44,
    justifyContent: 'center',
    elevation: 8,
    shadowColor: Colors.shadowMedium,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    borderWidth: 1,
  },
  actionButtonText: {
    color: Colors.white,
    fontSize: 12,
    fontFamily: Fonts.button,
    marginLeft: 6,
    fontWeight: '600',
  },
  editButton: {
    backgroundColor: Colors.blue500,
    borderColor: Colors.blue600,
  },
  shareButton: {
    backgroundColor: Colors.orange500,
    borderColor: Colors.orange600,
  },
  deleteButton: {
    backgroundColor: Colors.errorRed,
    borderColor: Colors.errorDark,
  },
  saveButton: {
    backgroundColor: Colors.successGreen,
    borderColor: Colors.successDark,
  },
  cancelButton: {
    backgroundColor: Colors.gray500,
    borderColor: Colors.gray600,
  },
});